import { Language } from '../types';

// Ana sayfa, üst menü, sayfalama ve giriş/kayıt penceresindeki yeni tasarım metinleri.
// Ortak etiketler translations.ts içinde; burada yalnızca yeni ihtiyaçlar var.
const tr = {
  heroTitleA: "Padova'da öğrenci evi,",
  heroTitleB: 'adil fiyata.',
  heroSub: 'Video turlu, UniPD onaylı ilanlar. Kiralar Padova öğrenci kira tablosuyla otomatik karşılaştırılır.',
  radarLabel: 'Fiyat Radarı',
  radarNote: 'için Padova rayiç ortalaması. Fahiş fiyatlar ilanda işaretlenir.',
  searchBtn: 'Ara',
  areaField: 'Bölge / Fakülte',
  searchField: 'Sokak / Semt',
  maxRentField: 'Maks. kira',
  allFilters: 'Tüm filtreler',
  recentTitle: 'Son eklenenler',
  newBadge: 'Yeni',
  allListingsTitle: 'Tüm ilanlar',
  rangeSummary: 'Sayfa {page} / {pages} · {from}–{to} arası, toplam {total} ilan',
  totalSummary: '{total} ilan',
  listView: 'Liste',
  mapView: 'Harita',
  pagesLabel: 'Sayfalar',
  prevPage: 'Önceki sayfa',
  nextPage: 'Sonraki sayfa',
  goToPage: '{n}. sayfaya git',
  photoWord: 'fotoğraf',
  videoTour30: '30 sn video tur',
  billsIncluded: 'Giderler dahil',
  billsExtra: 'Giderler hariç',
  authTabLogin: 'Giriş yap',
  authTabRegister: 'Kayıt ol',
  navExplore: 'Keşfet',
  guestLogin: 'Giriş Yap',
  postAd: 'İlan Ver',
  previewTitle: 'Hızlı önizleme',
  seeFullListing: 'İlanın tamamını gör',
  photosTab: 'Fotoğraflar',
  videoTab: '30 sn video tur',
  keysHint: '← → ile fotoğraf değiştir · Esc ile kapat',
  viewToggle: 'Görünüm',
  mainMenu: 'Ana menü',
};

type Dict = typeof tr;

const en: Dict = {
  heroTitleA: 'Student housing in Padova,',
  heroTitleB: 'at a fair price.',
  heroSub: 'Video-toured, UniPD-verified listings. Rents are compared with the Padova student rent table automatically.',
  radarLabel: 'Price radar',
  radarNote: 'is the Padova market average. Overpriced listings get flagged.',
  searchBtn: 'Search',
  areaField: 'Area / Faculty',
  searchField: 'Street / District',
  maxRentField: 'Max. rent',
  allFilters: 'All filters',
  recentTitle: 'Recently added',
  newBadge: 'New',
  allListingsTitle: 'All listings',
  rangeSummary: 'Page {page} / {pages} · {from}–{to} of {total} listings',
  totalSummary: '{total} listings',
  listView: 'List',
  mapView: 'Map',
  pagesLabel: 'Pages',
  prevPage: 'Previous page',
  nextPage: 'Next page',
  goToPage: 'Go to page {n}',
  photoWord: 'photos',
  videoTour30: '30 s video tour',
  billsIncluded: 'Bills included',
  billsExtra: 'Bills not included',
  authTabLogin: 'Log in',
  authTabRegister: 'Sign up',
  navExplore: 'Explore',
  guestLogin: 'Log in',
  postAd: 'Post a listing',
  previewTitle: 'Quick preview',
  seeFullListing: 'See the full listing',
  photosTab: 'Photos',
  videoTab: '30 s video tour',
  keysHint: '← → to change photo · Esc to close',
  viewToggle: 'View',
  mainMenu: 'Main menu',
};

const it: Dict = {
  heroTitleA: 'Casa per studenti a Padova,',
  heroTitleB: 'a un prezzo giusto.',
  heroSub: 'Annunci con video tour e verificati UniPD. Gli affitti sono confrontati con la tabella affitti studenti di Padova.',
  radarLabel: 'Radar prezzi',
  radarNote: 'è la media di mercato a Padova. Gli annunci troppo cari vengono segnalati.',
  searchBtn: 'Cerca',
  areaField: 'Zona / Facoltà',
  searchField: 'Via / Zona',
  maxRentField: 'Affitto max',
  allFilters: 'Tutti i filtri',
  recentTitle: 'Aggiunti di recente',
  newBadge: 'Nuovo',
  allListingsTitle: 'Tutti gli annunci',
  rangeSummary: 'Pagina {page} / {pages} · {from}–{to} di {total} annunci',
  totalSummary: '{total} annunci',
  listView: 'Elenco',
  mapView: 'Mappa',
  pagesLabel: 'Pagine',
  prevPage: 'Pagina precedente',
  nextPage: 'Pagina successiva',
  goToPage: 'Vai a pagina {n}',
  photoWord: 'foto',
  videoTour30: 'Video tour 30 s',
  billsIncluded: 'Spese incluse',
  billsExtra: 'Spese escluse',
  authTabLogin: 'Accedi',
  authTabRegister: 'Registrati',
  navExplore: 'Esplora',
  guestLogin: 'Accedi',
  postAd: 'Pubblica annuncio',
  previewTitle: 'Anteprima rapida',
  seeFullListing: "Vedi l'annuncio completo",
  photosTab: 'Foto',
  videoTab: 'Video tour 30 s',
  keysHint: '← → per cambiare foto · Esc per chiudere',
  viewToggle: 'Vista',
  mainMenu: 'Menu principale',
};

const de: Dict = {
  heroTitleA: 'Studentenwohnen in Padua,',
  heroTitleB: 'zum fairen Preis.',
  heroSub: 'Inserate mit Video-Tour und UniPD-Verifizierung. Die Mieten werden automatisch mit der Miettabelle für Studierende in Padua verglichen.',
  radarLabel: 'Preisradar',
  radarNote: 'ist der Marktdurchschnitt in Padua. Überteuerte Inserate werden markiert.',
  searchBtn: 'Suchen',
  areaField: 'Viertel / Fakultät',
  searchField: 'Straße / Viertel',
  maxRentField: 'Max. Miete',
  allFilters: 'Alle Filter',
  recentTitle: 'Neu eingestellt',
  newBadge: 'Neu',
  allListingsTitle: 'Alle Inserate',
  rangeSummary: 'Seite {page} / {pages} · {from}–{to} von {total} Inseraten',
  totalSummary: '{total} Inserate',
  listView: 'Liste',
  mapView: 'Karte',
  pagesLabel: 'Seiten',
  prevPage: 'Vorherige Seite',
  nextPage: 'Nächste Seite',
  goToPage: 'Zu Seite {n}',
  photoWord: 'Fotos',
  videoTour30: '30-Sek.-Videotour',
  billsIncluded: 'Nebenkosten inklusive',
  billsExtra: 'Nebenkosten extra',
  authTabLogin: 'Anmelden',
  authTabRegister: 'Registrieren',
  navExplore: 'Entdecken',
  guestLogin: 'Anmelden',
  postAd: 'Inserat aufgeben',
  previewTitle: 'Schnellvorschau',
  seeFullListing: 'Ganzes Inserat ansehen',
  photosTab: 'Fotos',
  videoTab: '30-Sek.-Videotour',
  keysHint: '← → Foto wechseln · Esc schließen',
  viewToggle: 'Ansicht',
  mainMenu: 'Hauptmenü',
};

const ru: Dict = {
  heroTitleA: 'Студенческое жильё в Падуе',
  heroTitleB: 'по честной цене.',
  heroSub: 'Объявления с видеотуром и подтверждением UniPD. Аренда автоматически сравнивается с таблицей студенческих цен Падуи.',
  radarLabel: 'Радар цен',
  radarNote: '— средняя рыночная цена в Падуе. Завышенные цены отмечаются.',
  searchBtn: 'Найти',
  areaField: 'Район / Факультет',
  searchField: 'Улица / Район',
  maxRentField: 'Макс. аренда',
  allFilters: 'Все фильтры',
  recentTitle: 'Недавно добавлены',
  newBadge: 'Новое',
  allListingsTitle: 'Все объявления',
  rangeSummary: 'Страница {page} / {pages} · {from}–{to} из {total} объявлений',
  totalSummary: 'Объявлений: {total}',
  listView: 'Список',
  mapView: 'Карта',
  pagesLabel: 'Страницы',
  prevPage: 'Предыдущая страница',
  nextPage: 'Следующая страница',
  goToPage: 'Перейти на страницу {n}',
  photoWord: 'фото',
  videoTour30: 'Видеотур 30 с',
  billsIncluded: 'Коммунальные включены',
  billsExtra: 'Коммунальные отдельно',
  authTabLogin: 'Вход',
  authTabRegister: 'Регистрация',
  navExplore: 'Поиск',
  guestLogin: 'Войти',
  postAd: 'Подать объявление',
  previewTitle: 'Быстрый просмотр',
  seeFullListing: 'Открыть объявление',
  photosTab: 'Фото',
  videoTab: 'Видеотур 30 с',
  keysHint: '← → листать фото · Esc закрыть',
  viewToggle: 'Вид',
  mainMenu: 'Главное меню',
};

const hi: Dict = {
  heroTitleA: 'पादोवा में छात्र आवास,',
  heroTitleB: 'सही कीमत पर।',
  heroSub: 'वीडियो टूर और UniPD सत्यापन वाले विज्ञापन। किराया पादोवा की छात्र किराया तालिका से अपने आप मिलाया जाता है।',
  radarLabel: 'प्राइस रडार',
  radarNote: 'पादोवा का औसत बाज़ार किराया है। ज़्यादा कीमत वाले विज्ञापन चिह्नित होते हैं।',
  searchBtn: 'खोजें',
  areaField: 'क्षेत्र / संकाय',
  searchField: 'सड़क / क्षेत्र',
  maxRentField: 'अधिकतम किराया',
  allFilters: 'सभी फ़िल्टर',
  recentTitle: 'हाल में जोड़े गए',
  newBadge: 'नया',
  allListingsTitle: 'सभी विज्ञापन',
  rangeSummary: 'पृष्ठ {page} / {pages} · कुल {total} में से {from}–{to}',
  totalSummary: '{total} विज्ञापन',
  listView: 'सूची',
  mapView: 'नक्शा',
  pagesLabel: 'पृष्ठ',
  prevPage: 'पिछला पृष्ठ',
  nextPage: 'अगला पृष्ठ',
  goToPage: 'पृष्ठ {n} पर जाएँ',
  photoWord: 'फ़ोटो',
  videoTour30: '30 सेकंड वीडियो टूर',
  billsIncluded: 'खर्च शामिल',
  billsExtra: 'खर्च अलग',
  authTabLogin: 'लॉग इन',
  authTabRegister: 'रजिस्टर',
  navExplore: 'खोजें',
  guestLogin: 'लॉग इन',
  postAd: 'विज्ञापन दें',
  previewTitle: 'त्वरित पूर्वावलोकन',
  seeFullListing: 'पूरा विज्ञापन देखें',
  photosTab: 'फ़ोटो',
  videoTab: '30 सेकंड वीडियो टूर',
  keysHint: '← → से फ़ोटो बदलें · Esc से बंद करें',
  viewToggle: 'दृश्य',
  mainMenu: 'मुख्य मेनू',
};

export const HOME_TEXT: Record<Language, Dict> = { tr, en, it, de, ru, hi };
export type HomeText = Dict;

export const fillText = (text: string, vars: Record<string, string | number>) =>
  text.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));
