import { Language } from '../types';

// İlan verme sihirbazına özel metinler. Ortak etiketler (semt, oda tipi, sözleşme türü vb.)
// translations.ts içinde zaten var; burada yalnızca sihirbazın yeni ihtiyaçları bulunur.
const tr = {
  createTitle: 'İlan ver',
  editTitle: 'İlanı düzenle',
  stepOf: 'Adım {n} / {total}',
  step1: 'Temel bilgi',
  step2: 'Fiyat ve sözleşme',
  step3: 'Ev detayları',
  step4: 'Fotoğraf ve video',
  step5: 'Ev arkadaşları',
  step6: 'Önizleme',
  step1Hint: 'Ne kiralıyorsun ve nerede?',
  step2Hint: 'Kira, giderler ve sözleşme süresi',
  step3Hint: 'Metrekare, olanaklar ve kurallar',
  step4Hint: 'İyi fotoğraf ilanı öne çıkarır',
  step5Hint: 'Evde kimler var, kimi arıyorsun?',
  step6Hint: 'Son kontrol ve yayınla',
  back: 'Geri',
  next: 'Kaydet ve devam et',
  publish: 'İlanı yayınla',
  saveChanges: 'Değişiklikleri kaydet',
  publishing: 'Yayınlanıyor…',
  saving: 'Kaydediliyor…',
  draftSaved: 'Taslak kaydedildi',
  close: 'Kapat',
  preview: 'Önizle',
  livePreview: 'Canlı önizleme',
  previewNote: 'İlanın aramada böyle görünecek.',
  required: 'Zorunlu',
  optional: 'İsteğe bağlı',
  fixFields: 'Devam etmeden önce işaretli alanları tamamla.',

  roomTypeQ: 'Ne tür bir oda?',
  titleLabel: 'İlan başlığı',
  titleHelp: 'Kısa ve net: sokak, oda tipi ve öne çıkan bir özellik.',
  titlePlaceholder: 'Via Forcellini, ışıklı tek kişilik oda',
  titleError: 'Bir başlık yaz.',
  locationLabel: 'Adres',
  locationHelp: 'Adres yaz ya da haritada pini sürükle. Semt otomatik dolar.',
  addressPlaceholder: 'Via Forcellini 42, Padova',
  suggestions: 'Öneriler',
  districtLabel: 'Semt',
  districtAuto: 'Konuma göre seçildi',
  nearestUni: 'En yakın üniversite binası',
  walk: 'yürüyerek',
  bus: 'otobüsle ≈',
  min: 'dk',

  rentLabel: 'Aylık kira',
  rentError: 'Kira tutarını gir.',
  perMonth: '/ ay',
  expensesLabel: 'Giderler',
  expensesIncluded: 'Kiraya dahil',
  expensesExtra: 'Ayrıca ödenir',
  expensesAmount: 'Aylık gider tutarı',
  expensesIncludedText: 'Giderler dahil',
  expensesExtraText: 'Giderler',
  radarTitle: 'Kira Endeksi',
  radarNoData: 'Bu oda tipi için karşılaştırma verisi yok.',
  radarAvg: 'Bölge ortalaması',
  radarLow: 'Uygun',
  radarFair: 'Adil',
  radarHigh: 'Pahalı',
  radarLowMsg: 'Bölge ortalamasının altında: hızlı ilgi görür.',
  radarFairMsg: 'Bölge ortalamasında: adil bir fiyat.',
  radarHighMsg: 'Bölge ortalamasının üstünde: ilgi azalabilir.',
  radarEmpty: 'Kirayı ve metrekareyi girince bölgenin m² başına ortalamasıyla karşılaştırırız.',
  radarNeedArea: 'Karşılaştırma için bir sonraki adımda metrekareyi girin (Singola/Doppia: oda, Monolocale/Bilocale: evin tamamı).',
  contractLabel: 'Sözleşme türü',
  datesLabel: 'Sözleşme dönemi',
  datesHelp: 'Başlangıç ve bitiş tarihini takvimden seç.',
  startLabel: 'Başlangıç',
  endLabel: 'Bitiş',
  datesRequired: 'Başlangıç ve bitiş tarihi zorunlu. Süresiz ilan verilemez.',
  duration: 'Süre',
  months: 'ay',
  monthsUnit_one: '{n} ay',
  monthsUnit_other: '{n} ay',
  clearDates: 'Tarihleri temizle',
  pickStartFirst: 'Önce başlangıç gününü seç',
  pickEnd: 'Şimdi bitiş gününü seç',
  endBeforeStart: 'Bitiş, başlangıçtan sonra olmalı.',

  roomAreaLabel: 'Oda (m²)',
  aptAreaLabel: 'Daire (m²)',
  bathroomsLabel: 'Banyo',
  areaError: 'Gir',
  heatingLabel: 'Isıtma',
  amenitiesLabel: 'Olanaklar',
  groupComfort: 'Konfor',
  groupMobility: 'Ulaşım',
  groupRules: 'Ev kuralları',
  bikeDetailsPlaceholder: 'Nerede? Örn. kapalı avlu',
  parkingDetailsPlaceholder: 'Nasıl? Örn. garaj, sokak izni',
  descriptionLabel: 'Açıklama',
  descriptionHelp: 'Evi, komşuluğu ve sözleşme koşullarını anlat.',
  descriptionPlaceholder: 'Evin genel hali, ulaşım, sözleşme detayları…',
  smokingOk: 'Sigara serbest',
  smokingNo: 'Sigara yasak',
  petsOk: 'Evcil hayvan serbest',
  petsNo: 'Evcil hayvan yok',

  photosLabel: 'Fotoğraflar',
  photosHelp: 'İlk fotoğraf kapak olur. Sürükleyerek sırayı değiştirebilirsin.',
  photosTips: 'Yatay çek, gün ışığında, odayı, mutfağı ve banyoyu göster. En az 3 fotoğraf önerilir.',
  dropHere: 'Fotoğrafları buraya bırak',
  orBrowse: 'ya da cihazdan seç',
  addByUrl: 'Bağlantıyla ekle',
  urlPlaceholder: 'https://…/foto.jpg',
  add: 'Ekle',
  cover: 'Kapak',
  makeCover: 'Kapak yap',
  remove: 'Sil',
  moveLeft: 'Sola taşı',
  moveRight: 'Sağa taşı',
  uploading: 'Yükleniyor',
  uploadFailed: 'Yüklenemedi',
  similarBadge: 'Benzer fotoğraf',
  similarNote: 'Bazı fotoğrafların başka bir ilanda da kullanıldığı görüldü. Yalnızca kendi çektiğin fotoğrafları kullan; başkasına ait fotoğraflar ilanın kaldırılmasına ve hesabın kapatılmasına yol açabilir.',
  retry: 'Tekrar dene',
  photoError: 'En az bir fotoğraf ekle.',
  photoCount: '{n} fotoğraf',
  videoTitle: 'Video tur',
  videoDesc: 'Video turlu ilanlar daha çok ilgi görür. Odayı ve ortak alanları gezdiren kısa bir video bağlantısı ekle.',
  videoToggle: 'Video tur ekle',
  videoUrlLabel: 'Video bağlantısı',
  videoUrlHelp: 'MP4 / WebM dosya bağlantısı. 30-90 saniye idealdir.',
  moreAngles: 'Farklı açılar ekle',
  angleDesk: 'Çalışma masası',
  angleKitchen: 'Mutfak / ortak alan',
  angleBalcony: 'Balkon / manzara',

  housematesLabel: 'Evde kaç kişi kalıyor?',
  housematesHelp: 'Seni de sayarak toplam kişi sayısı.',
  distributionLabel: 'Cinsiyet dağılımı',
  distributionHelp: 'Şu an evde kalanlar.',
  women: 'Kadın',
  men: 'Erkek',
  genderPrefLabel: 'Kimi arıyorsun?',
  genderAny: 'Fark etmez',
  genderFemale: 'Sadece kadın',
  genderMale: 'Sadece erkek',
  occupantLabel: 'Ev sakinleri',
  occStudents: 'Sadece öğrenci',
  occMixed: 'Karışık',
  occWorkers: 'Çalışan',

  reviewTitle: 'Her şey hazır mı?',
  reviewHint: 'Yayınlamadan önce özet bilgilere göz at.',
  edit: 'Düzenle',
  checklistTitle: 'İlan kalitesi',
  checkPhotos: '3+ fotoğraf',
  checkVideo: 'Video tur',
  checkDescription: 'Açıklama',
  checkDates: 'Sözleşme tarihleri',
  loginBtn: 'Giriş yap / Kayıt ol',
  draftRestored: 'Kaldığın yerden devam ediyorsun.',
  discardDraft: 'Taslağı sil',

  successTitle: 'İlanın yayında!',
  successEdit: 'Değişiklikler kaydedildi',
  successText: 'İlanın Padova öğrenci ağında görünüyor. Bağlantıyı paylaşarak daha hızlı ilgi topla.',
  copyLink: 'Bağlantıyı kopyala',
  copied: 'Kopyalandı',
  share: 'Paylaş',
  viewListing: 'İlanı gör',
  boostTitle: 'İlanını güçlendir',
  boostVideo: 'Video tur ekle',
  boostVideoDesc: 'Video turlu ilanlar daha çok mesaj alır.',
  boostVerify: 'UniPD doğrulaması yap',
  boostVerifyDesc: 'Doğrulanmış öğrenci rozeti güven verir.',
  boostPhotos: 'Daha fazla fotoğraf ekle',
  boostPhotosDesc: 'Her odanın bir fotoğrafı olsun.',
  toMyListings: 'İlanlarım',
};

type Dict = typeof tr;

const en: Dict = {
  createTitle: 'Post a listing',
  editTitle: 'Edit listing',
  stepOf: 'Step {n} of {total}',
  step1: 'Basics',
  step2: 'Price & contract',
  step3: 'Home details',
  step4: 'Photos & video',
  step5: 'Housemates',
  step6: 'Preview',
  step1Hint: 'What are you renting and where?',
  step2Hint: 'Rent, bills and contract period',
  step3Hint: 'Size, amenities and house rules',
  step4Hint: 'Good photos make your listing stand out',
  step5Hint: 'Who lives there, who are you looking for?',
  step6Hint: 'Final check and publish',
  back: 'Back',
  next: 'Save and continue',
  publish: 'Publish listing',
  saveChanges: 'Save changes',
  publishing: 'Publishing…',
  saving: 'Saving…',
  draftSaved: 'Draft saved',
  close: 'Close',
  preview: 'Preview',
  livePreview: 'Live preview',
  previewNote: 'This is how your listing will look in search.',
  required: 'Required',
  optional: 'Optional',
  fixFields: 'Complete the highlighted fields before continuing.',

  roomTypeQ: 'What kind of room?',
  titleLabel: 'Listing title',
  titleHelp: 'Short and clear: street, room type and one highlight.',
  titlePlaceholder: 'Via Forcellini, bright single room',
  titleError: 'Add a title.',
  locationLabel: 'Address',
  locationHelp: 'Type an address or drag the pin on the map. The area fills in automatically.',
  addressPlaceholder: 'Via Forcellini 42, Padova',
  suggestions: 'Suggestions',
  districtLabel: 'Area',
  districtAuto: 'Picked from the location',
  nearestUni: 'Nearest university building',
  walk: 'on foot',
  bus: 'by bus ≈',
  min: 'min',

  rentLabel: 'Monthly rent',
  rentError: 'Enter the rent.',
  perMonth: '/ month',
  expensesLabel: 'Bills',
  expensesIncluded: 'Included in rent',
  expensesExtra: 'Paid separately',
  expensesAmount: 'Monthly bills amount',
  expensesIncludedText: 'Bills included',
  expensesExtraText: 'Utilities',
  radarTitle: 'Rent index',
  radarNoData: 'No comparison data for this room type.',
  radarAvg: 'Area average',
  radarLow: 'Good deal',
  radarFair: 'Fair',
  radarHigh: 'High',
  radarLowMsg: 'Below the area average: expect quick interest.',
  radarFairMsg: 'In line with the area average: a fair price.',
  radarHighMsg: 'Above the area average: interest may be lower.',
  radarEmpty: 'Enter the rent and the size and we compare it with the area’s average per m².',
  radarNeedArea: 'Enter the size in the next step to compare (Singola/Doppia: room, Monolocale/Bilocale: whole home).',
  contractLabel: 'Contract type',
  datesLabel: 'Contract period',
  datesHelp: 'Pick the start and end dates on the calendar.',
  startLabel: 'Start',
  endLabel: 'End',
  datesRequired: 'Start and end dates are required. Open-ended listings are not allowed.',
  duration: 'Duration',
  months: 'months',
  monthsUnit_one: '{n} month',
  monthsUnit_other: '{n} months',
  clearDates: 'Clear dates',
  pickStartFirst: 'Pick the start day first',
  pickEnd: 'Now pick the end day',
  endBeforeStart: 'End must be after the start.',

  roomAreaLabel: 'Room (m²)',
  aptAreaLabel: 'Apartment (m²)',
  bathroomsLabel: 'Bathrooms',
  areaError: 'Enter',
  heatingLabel: 'Heating',
  amenitiesLabel: 'Amenities',
  groupComfort: 'Comfort',
  groupMobility: 'Getting around',
  groupRules: 'House rules',
  bikeDetailsPlaceholder: 'Where? e.g. closed courtyard',
  parkingDetailsPlaceholder: 'How? e.g. garage, street permit',
  descriptionLabel: 'Description',
  descriptionHelp: 'Describe the home, the neighborhood and the contract terms.',
  descriptionPlaceholder: 'General feel of the home, transport, contract details…',
  smokingOk: 'Smoking allowed',
  smokingNo: 'No smoking',
  petsOk: 'Pets allowed',
  petsNo: 'No pets',

  photosLabel: 'Photos',
  photosHelp: 'The first photo is the cover. Drag to reorder.',
  photosTips: 'Shoot landscape in daylight and show the room, kitchen and bathroom. At least 3 photos recommended.',
  dropHere: 'Drop photos here',
  orBrowse: 'or choose from your device',
  addByUrl: 'Add by link',
  urlPlaceholder: 'https://…/photo.jpg',
  add: 'Add',
  cover: 'Cover',
  makeCover: 'Make cover',
  remove: 'Remove',
  moveLeft: 'Move left',
  moveRight: 'Move right',
  uploading: 'Uploading',
  uploadFailed: 'Upload failed',
  similarBadge: 'Similar photo',
  similarNote: 'Some photos appear to be used in another listing too. Only use photos you took yourself; using someone else\'s photos can lead to your listing being removed and your account being closed.',
  retry: 'Retry',
  photoError: 'Add at least one photo.',
  photoCount: '{n} photos',
  videoTitle: 'Video tour',
  videoDesc: 'Listings with a video tour get more interest. Add a link to a short video walking through the room and shared areas.',
  videoToggle: 'Add a video tour',
  videoUrlLabel: 'Video link',
  videoUrlHelp: 'MP4 / WebM file link. 30-90 seconds is ideal.',
  moreAngles: 'Add more angles',
  angleDesk: 'Desk',
  angleKitchen: 'Kitchen / shared area',
  angleBalcony: 'Balcony / view',

  housematesLabel: 'How many people live there?',
  housematesHelp: 'Total number of people, including you.',
  distributionLabel: 'Gender mix',
  distributionHelp: 'Who lives there now.',
  women: 'Women',
  men: 'Men',
  genderPrefLabel: 'Who are you looking for?',
  genderAny: 'No preference',
  genderFemale: 'Women only',
  genderMale: 'Men only',
  occupantLabel: 'Residents',
  occStudents: 'Students only',
  occMixed: 'Mixed',
  occWorkers: 'Working people',

  reviewTitle: 'Everything ready?',
  reviewHint: 'Take a look at the summary before publishing.',
  edit: 'Edit',
  checklistTitle: 'Listing quality',
  checkPhotos: '3+ photos',
  checkVideo: 'Video tour',
  checkDescription: 'Description',
  checkDates: 'Contract dates',
  loginBtn: 'Sign in / Register',
  draftRestored: 'Picking up where you left off.',
  discardDraft: 'Discard draft',

  successTitle: 'Your listing is live!',
  successEdit: 'Changes saved',
  successText: 'Your listing is now visible on the Padova student network. Share the link to get interest faster.',
  copyLink: 'Copy link',
  copied: 'Copied',
  share: 'Share',
  viewListing: 'View listing',
  boostTitle: 'Boost your listing',
  boostVideo: 'Add a video tour',
  boostVideoDesc: 'Listings with video get more messages.',
  boostVerify: 'Verify with UniPD',
  boostVerifyDesc: 'A verified student badge builds trust.',
  boostPhotos: 'Add more photos',
  boostPhotosDesc: 'Give every room a photo.',
  toMyListings: 'My listings',
};

const it: Dict = {
  createTitle: 'Pubblica annuncio',
  editTitle: 'Modifica annuncio',
  stepOf: 'Passo {n} di {total}',
  step1: 'Info di base',
  step2: 'Prezzo e contratto',
  step3: 'Dettagli casa',
  step4: 'Foto e video',
  step5: 'Coinquilini',
  step6: 'Anteprima',
  step1Hint: 'Cosa affitti e dove?',
  step2Hint: 'Affitto, spese e durata del contratto',
  step3Hint: 'Metri quadri, dotazioni e regole',
  step4Hint: 'Belle foto fanno risaltare l’annuncio',
  step5Hint: 'Chi vive in casa, chi cerchi?',
  step6Hint: 'Controllo finale e pubblicazione',
  back: 'Indietro',
  next: 'Salva e continua',
  publish: 'Pubblica annuncio',
  saveChanges: 'Salva modifiche',
  publishing: 'Pubblicazione…',
  saving: 'Salvataggio…',
  draftSaved: 'Bozza salvata',
  close: 'Chiudi',
  preview: 'Anteprima',
  livePreview: 'Anteprima live',
  previewNote: 'Così apparirà il tuo annuncio nella ricerca.',
  required: 'Obbligatorio',
  optional: 'Facoltativo',
  fixFields: 'Completa i campi evidenziati prima di continuare.',

  roomTypeQ: 'Che tipo di stanza?',
  titleLabel: 'Titolo dell’annuncio',
  titleHelp: 'Breve e chiaro: via, tipo di stanza e un punto di forza.',
  titlePlaceholder: 'Via Forcellini, singola luminosa',
  titleError: 'Aggiungi un titolo.',
  locationLabel: 'Indirizzo',
  locationHelp: 'Scrivi un indirizzo o trascina il pin sulla mappa. La zona si compila da sola.',
  addressPlaceholder: 'Via Forcellini 42, Padova',
  suggestions: 'Suggerimenti',
  districtLabel: 'Zona',
  districtAuto: 'Scelta in base alla posizione',
  nearestUni: 'Sede universitaria più vicina',
  walk: 'a piedi',
  bus: 'in bus ≈',
  min: 'min',

  rentLabel: 'Affitto mensile',
  rentError: 'Inserisci l’affitto.',
  perMonth: '/ mese',
  expensesLabel: 'Spese',
  expensesIncluded: 'Incluse nell’affitto',
  expensesExtra: 'A parte',
  expensesAmount: 'Importo mensile delle spese',
  expensesIncludedText: 'Spese incluse',
  expensesExtraText: 'Spese',
  radarTitle: 'Indice affitti',
  radarNoData: 'Nessun dato di confronto per questo tipo di stanza.',
  radarAvg: 'Media della zona',
  radarLow: 'Conveniente',
  radarFair: 'Giusto',
  radarHigh: 'Alto',
  radarLowMsg: 'Sotto la media della zona: interesse rapido.',
  radarFairMsg: 'In linea con la media della zona: prezzo giusto.',
  radarHighMsg: 'Sopra la media della zona: l’interesse potrebbe calare.',
  radarEmpty: 'Inserisci affitto e metratura e li confrontiamo con la media della zona al m².',
  radarNeedArea: 'Inserisci la metratura nel passo successivo per il confronto (Singola/Doppia: stanza, Monolocale/Bilocale: intero appartamento).',
  contractLabel: 'Tipo di contratto',
  datesLabel: 'Periodo del contratto',
  datesHelp: 'Scegli data di inizio e fine dal calendario.',
  startLabel: 'Inizio',
  endLabel: 'Fine',
  datesRequired: 'Le date di inizio e fine sono obbligatorie. Non sono ammessi annunci senza scadenza.',
  duration: 'Durata',
  months: 'mesi',
  monthsUnit_one: '{n} mese',
  monthsUnit_other: '{n} mesi',
  clearDates: 'Cancella date',
  pickStartFirst: 'Scegli prima il giorno di inizio',
  pickEnd: 'Ora scegli il giorno di fine',
  endBeforeStart: 'La fine deve essere dopo l’inizio.',

  roomAreaLabel: 'Stanza (m²)',
  aptAreaLabel: 'Appartamento (m²)',
  bathroomsLabel: 'Bagni',
  areaError: 'Inserisci',
  heatingLabel: 'Riscaldamento',
  amenitiesLabel: 'Dotazioni',
  groupComfort: 'Comfort',
  groupMobility: 'Spostamenti',
  groupRules: 'Regole della casa',
  bikeDetailsPlaceholder: 'Dove? Es. cortile chiuso',
  parkingDetailsPlaceholder: 'Come? Es. garage, permesso in strada',
  descriptionLabel: 'Descrizione',
  descriptionHelp: 'Descrivi la casa, il quartiere e le condizioni del contratto.',
  descriptionPlaceholder: 'Aspetto generale, trasporti, dettagli del contratto…',
  smokingOk: 'Si può fumare',
  smokingNo: 'Vietato fumare',
  petsOk: 'Animali ammessi',
  petsNo: 'Niente animali',

  photosLabel: 'Foto',
  photosHelp: 'La prima foto è la copertina. Trascina per riordinare.',
  photosTips: 'Scatta in orizzontale con luce naturale e mostra stanza, cucina e bagno. Consigliate almeno 3 foto.',
  dropHere: 'Rilascia qui le foto',
  orBrowse: 'oppure scegli dal dispositivo',
  addByUrl: 'Aggiungi da link',
  urlPlaceholder: 'https://…/foto.jpg',
  add: 'Aggiungi',
  cover: 'Copertina',
  makeCover: 'Imposta copertina',
  remove: 'Rimuovi',
  moveLeft: 'Sposta a sinistra',
  moveRight: 'Sposta a destra',
  uploading: 'Caricamento',
  uploadFailed: 'Caricamento non riuscito',
  similarBadge: 'Foto simile',
  similarNote: 'Alcune foto risultano usate anche in un altro annuncio. Usa solo foto scattate da te: usare foto altrui può portare alla rimozione dell\'annuncio e alla chiusura dell\'account.',
  retry: 'Riprova',
  photoError: 'Aggiungi almeno una foto.',
  photoCount: '{n} foto',
  videoTitle: 'Video tour',
  videoDesc: 'Gli annunci con video tour ricevono più interesse. Aggiungi il link a un breve video della stanza e degli spazi comuni.',
  videoToggle: 'Aggiungi video tour',
  videoUrlLabel: 'Link del video',
  videoUrlHelp: 'Link a file MP4 / WebM. Ideale 30-90 secondi.',
  moreAngles: 'Aggiungi altre angolazioni',
  angleDesk: 'Scrivania',
  angleKitchen: 'Cucina / spazi comuni',
  angleBalcony: 'Balcone / vista',

  housematesLabel: 'Quante persone vivono in casa?',
  housematesHelp: 'Numero totale, te compreso.',
  distributionLabel: 'Composizione per genere',
  distributionHelp: 'Chi vive in casa ora.',
  women: 'Donne',
  men: 'Uomini',
  genderPrefLabel: 'Chi cerchi?',
  genderAny: 'Indifferente',
  genderFemale: 'Solo donne',
  genderMale: 'Solo uomini',
  occupantLabel: 'Inquilini',
  occStudents: 'Solo studenti',
  occMixed: 'Misto',
  occWorkers: 'Lavoratori',

  reviewTitle: 'Tutto pronto?',
  reviewHint: 'Dai un’occhiata al riepilogo prima di pubblicare.',
  edit: 'Modifica',
  checklistTitle: 'Qualità dell’annuncio',
  checkPhotos: '3+ foto',
  checkVideo: 'Video tour',
  checkDescription: 'Descrizione',
  checkDates: 'Date del contratto',
  loginBtn: 'Accedi / Registrati',
  draftRestored: 'Riprendi da dove eri rimasto.',
  discardDraft: 'Elimina bozza',

  successTitle: 'Il tuo annuncio è online!',
  successEdit: 'Modifiche salvate',
  successText: 'Il tuo annuncio è visibile nella rete studenti di Padova. Condividi il link per ricevere più interesse.',
  copyLink: 'Copia link',
  copied: 'Copiato',
  share: 'Condividi',
  viewListing: 'Vedi annuncio',
  boostTitle: 'Potenzia il tuo annuncio',
  boostVideo: 'Aggiungi video tour',
  boostVideoDesc: 'Gli annunci con video ricevono più messaggi.',
  boostVerify: 'Verifica con UniPD',
  boostVerifyDesc: 'Il badge studente verificato dà fiducia.',
  boostPhotos: 'Aggiungi altre foto',
  boostPhotosDesc: 'Una foto per ogni ambiente.',
  toMyListings: 'I miei annunci',
};

const de: Dict = {
  createTitle: 'Anzeige aufgeben',
  editTitle: 'Anzeige bearbeiten',
  stepOf: 'Schritt {n} von {total}',
  step1: 'Grunddaten',
  step2: 'Preis & Vertrag',
  step3: 'Wohnungsdetails',
  step4: 'Fotos & Video',
  step5: 'Mitbewohner',
  step6: 'Vorschau',
  step1Hint: 'Was vermietest du und wo?',
  step2Hint: 'Miete, Nebenkosten und Vertragszeitraum',
  step3Hint: 'Größe, Ausstattung und Hausregeln',
  step4Hint: 'Gute Fotos lassen deine Anzeige auffallen',
  step5Hint: 'Wer wohnt dort, wen suchst du?',
  step6Hint: 'Letzte Prüfung und Veröffentlichung',
  back: 'Zurück',
  next: 'Speichern und weiter',
  publish: 'Anzeige veröffentlichen',
  saveChanges: 'Änderungen speichern',
  publishing: 'Wird veröffentlicht…',
  saving: 'Wird gespeichert…',
  draftSaved: 'Entwurf gespeichert',
  close: 'Schließen',
  preview: 'Vorschau',
  livePreview: 'Live-Vorschau',
  previewNote: 'So erscheint deine Anzeige in der Suche.',
  required: 'Pflicht',
  optional: 'Optional',
  fixFields: 'Fülle die markierten Felder aus, bevor du weitergehst.',

  roomTypeQ: 'Was für ein Zimmer?',
  titleLabel: 'Titel der Anzeige',
  titleHelp: 'Kurz und klar: Straße, Zimmertyp und ein Highlight.',
  titlePlaceholder: 'Via Forcellini, helles Einzelzimmer',
  titleError: 'Gib einen Titel ein.',
  locationLabel: 'Adresse',
  locationHelp: 'Adresse eingeben oder Pin auf der Karte ziehen. Das Viertel wird automatisch gewählt.',
  addressPlaceholder: 'Via Forcellini 42, Padova',
  suggestions: 'Vorschläge',
  districtLabel: 'Viertel',
  districtAuto: 'Anhand des Standorts gewählt',
  nearestUni: 'Nächstes Uni-Gebäude',
  walk: 'zu Fuß',
  bus: 'mit dem Bus ≈',
  min: 'Min.',

  rentLabel: 'Monatsmiete',
  rentError: 'Gib die Miete ein.',
  perMonth: '/ Monat',
  expensesLabel: 'Nebenkosten',
  expensesIncluded: 'In der Miete enthalten',
  expensesExtra: 'Zusätzlich',
  expensesAmount: 'Monatliche Nebenkosten',
  expensesIncludedText: 'Nebenkosten inklusive',
  expensesExtraText: 'Nebenkosten',
  radarTitle: 'Mietindex',
  radarNoData: 'Keine Vergleichsdaten für diesen Zimmertyp.',
  radarAvg: 'Viertel-Durchschnitt',
  radarLow: 'Günstig',
  radarFair: 'Fair',
  radarHigh: 'Hoch',
  radarLowMsg: 'Unter dem Durchschnitt: schnelles Interesse zu erwarten.',
  radarFairMsg: 'Im Durchschnitt: ein fairer Preis.',
  radarHighMsg: 'Über dem Durchschnitt: weniger Interesse möglich.',
  radarEmpty: 'Gib Miete und Fläche ein, wir vergleichen sie mit dem Durchschnitt pro m².',
  radarNeedArea: 'Gib die Fläche im nächsten Schritt ein, um zu vergleichen (Singola/Doppia: Zimmer, Monolocale/Bilocale: ganze Wohnung).',
  contractLabel: 'Vertragsart',
  datesLabel: 'Vertragszeitraum',
  datesHelp: 'Wähle Start- und Enddatum im Kalender.',
  startLabel: 'Beginn',
  endLabel: 'Ende',
  datesRequired: 'Start- und Enddatum sind Pflicht. Unbefristete Anzeigen sind nicht erlaubt.',
  duration: 'Dauer',
  months: 'Monate',
  monthsUnit_one: '{n} Monat',
  monthsUnit_other: '{n} Monate',
  clearDates: 'Daten löschen',
  pickStartFirst: 'Wähle zuerst den Starttag',
  pickEnd: 'Wähle jetzt den Endtag',
  endBeforeStart: 'Das Ende muss nach dem Beginn liegen.',

  roomAreaLabel: 'Zimmer (m²)',
  aptAreaLabel: 'Wohnung (m²)',
  bathroomsLabel: 'Bäder',
  areaError: 'Angeben',
  heatingLabel: 'Heizung',
  amenitiesLabel: 'Ausstattung',
  groupComfort: 'Komfort',
  groupMobility: 'Mobilität',
  groupRules: 'Hausregeln',
  bikeDetailsPlaceholder: 'Wo? z. B. geschlossener Innenhof',
  parkingDetailsPlaceholder: 'Wie? z. B. Garage, Anwohnerparken',
  descriptionLabel: 'Beschreibung',
  descriptionHelp: 'Beschreibe die Wohnung, die Gegend und die Vertragsbedingungen.',
  descriptionPlaceholder: 'Allgemeiner Eindruck, Anbindung, Vertragsdetails…',
  smokingOk: 'Rauchen erlaubt',
  smokingNo: 'Nichtraucher',
  petsOk: 'Haustiere erlaubt',
  petsNo: 'Keine Haustiere',

  photosLabel: 'Fotos',
  photosHelp: 'Das erste Foto ist das Titelbild. Zum Sortieren ziehen.',
  photosTips: 'Im Querformat bei Tageslicht fotografieren und Zimmer, Küche und Bad zeigen. Mindestens 3 Fotos empfohlen.',
  dropHere: 'Fotos hier ablegen',
  orBrowse: 'oder vom Gerät auswählen',
  addByUrl: 'Per Link hinzufügen',
  urlPlaceholder: 'https://…/foto.jpg',
  add: 'Hinzufügen',
  cover: 'Titelbild',
  makeCover: 'Als Titelbild',
  remove: 'Entfernen',
  moveLeft: 'Nach links',
  moveRight: 'Nach rechts',
  uploading: 'Wird hochgeladen',
  uploadFailed: 'Upload fehlgeschlagen',
  similarBadge: 'Ähnliches Foto',
  similarNote: 'Einige Fotos werden offenbar auch in einer anderen Anzeige verwendet. Verwende nur selbst aufgenommene Fotos: Fremde Fotos können zur Löschung der Anzeige und zur Sperrung des Kontos führen.',
  retry: 'Erneut versuchen',
  photoError: 'Füge mindestens ein Foto hinzu.',
  photoCount: '{n} Fotos',
  videoTitle: 'Video-Rundgang',
  videoDesc: 'Anzeigen mit Video-Rundgang erhalten mehr Interesse. Füge einen Link zu einem kurzen Video von Zimmer und Gemeinschaftsräumen hinzu.',
  videoToggle: 'Video-Rundgang hinzufügen',
  videoUrlLabel: 'Video-Link',
  videoUrlHelp: 'Link zu MP4-/WebM-Datei. 30-90 Sekunden sind ideal.',
  moreAngles: 'Weitere Perspektiven hinzufügen',
  angleDesk: 'Schreibtisch',
  angleKitchen: 'Küche / Gemeinschaftsraum',
  angleBalcony: 'Balkon / Aussicht',

  housematesLabel: 'Wie viele Personen wohnen dort?',
  housematesHelp: 'Gesamtzahl inklusive dir.',
  distributionLabel: 'Geschlechterverteilung',
  distributionHelp: 'Wer aktuell dort wohnt.',
  women: 'Frauen',
  men: 'Männer',
  genderPrefLabel: 'Wen suchst du?',
  genderAny: 'Egal',
  genderFemale: 'Nur Frauen',
  genderMale: 'Nur Männer',
  occupantLabel: 'Bewohner',
  occStudents: 'Nur Studierende',
  occMixed: 'Gemischt',
  occWorkers: 'Berufstätige',

  reviewTitle: 'Alles bereit?',
  reviewHint: 'Wirf vor dem Veröffentlichen einen Blick auf die Zusammenfassung.',
  edit: 'Bearbeiten',
  checklistTitle: 'Anzeigenqualität',
  checkPhotos: '3+ Fotos',
  checkVideo: 'Video-Rundgang',
  checkDescription: 'Beschreibung',
  checkDates: 'Vertragsdaten',
  loginBtn: 'Anmelden / Registrieren',
  draftRestored: 'Du machst da weiter, wo du aufgehört hast.',
  discardDraft: 'Entwurf verwerfen',

  successTitle: 'Deine Anzeige ist online!',
  successEdit: 'Änderungen gespeichert',
  successText: 'Deine Anzeige ist jetzt im Paduaner Studierendennetzwerk sichtbar. Teile den Link für schnelleres Interesse.',
  copyLink: 'Link kopieren',
  copied: 'Kopiert',
  share: 'Teilen',
  viewListing: 'Anzeige ansehen',
  boostTitle: 'Anzeige aufwerten',
  boostVideo: 'Video-Rundgang hinzufügen',
  boostVideoDesc: 'Anzeigen mit Video bekommen mehr Nachrichten.',
  boostVerify: 'Mit UniPD verifizieren',
  boostVerifyDesc: 'Das Badge „verifizierter Student“ schafft Vertrauen.',
  boostPhotos: 'Mehr Fotos hinzufügen',
  boostPhotosDesc: 'Ein Foto für jeden Raum.',
  toMyListings: 'Meine Anzeigen',
};

const ru: Dict = {
  createTitle: 'Подать объявление',
  editTitle: 'Редактировать объявление',
  stepOf: 'Шаг {n} из {total}',
  step1: 'Основное',
  step2: 'Цена и договор',
  step3: 'О жилье',
  step4: 'Фото и видео',
  step5: 'Соседи',
  step6: 'Предпросмотр',
  step1Hint: 'Что и где вы сдаёте?',
  step2Hint: 'Аренда, коммунальные и срок договора',
  step3Hint: 'Площадь, удобства и правила',
  step4Hint: 'Хорошие фото выделяют объявление',
  step5Hint: 'Кто живёт и кого вы ищете?',
  step6Hint: 'Финальная проверка и публикация',
  back: 'Назад',
  next: 'Сохранить и продолжить',
  publish: 'Опубликовать',
  saveChanges: 'Сохранить изменения',
  publishing: 'Публикация…',
  saving: 'Сохранение…',
  draftSaved: 'Черновик сохранён',
  close: 'Закрыть',
  preview: 'Предпросмотр',
  livePreview: 'Живой предпросмотр',
  previewNote: 'Так объявление будет выглядеть в поиске.',
  required: 'Обязательно',
  optional: 'Необязательно',
  fixFields: 'Заполните отмеченные поля, чтобы продолжить.',

  roomTypeQ: 'Какая комната?',
  titleLabel: 'Заголовок',
  titleHelp: 'Коротко и ясно: улица, тип комнаты и главная особенность.',
  titlePlaceholder: 'Via Forcellini, светлая одноместная комната',
  titleError: 'Добавьте заголовок.',
  locationLabel: 'Адрес',
  locationHelp: 'Введите адрес или перетащите метку на карте. Район определится сам.',
  addressPlaceholder: 'Via Forcellini 42, Padova',
  suggestions: 'Подсказки',
  districtLabel: 'Район',
  districtAuto: 'Выбран по местоположению',
  nearestUni: 'Ближайший корпус университета',
  walk: 'пешком',
  bus: 'на автобусе ≈',
  min: 'мин',

  rentLabel: 'Аренда в месяц',
  rentError: 'Укажите сумму аренды.',
  perMonth: '/ мес.',
  expensesLabel: 'Коммунальные',
  expensesIncluded: 'Включены в аренду',
  expensesExtra: 'Оплачиваются отдельно',
  expensesAmount: 'Сумма коммунальных в месяц',
  expensesIncludedText: 'Коммунальные включены',
  expensesExtraText: 'Коммунальные',
  radarTitle: 'Индекс аренды',
  radarNoData: 'Нет данных для сравнения по этому типу комнаты.',
  radarAvg: 'Среднее по району',
  radarLow: 'Выгодно',
  radarFair: 'Справедливо',
  radarHigh: 'Дорого',
  radarLowMsg: 'Ниже среднего по району: интерес будет быстрым.',
  radarFairMsg: 'На уровне среднего по району: справедливая цена.',
  radarHighMsg: 'Выше среднего по району: интерес может снизиться.',
  radarEmpty: 'Укажите аренду и площадь, и мы сравним с средней ценой за м² по району.',
  radarNeedArea: 'Укажите площадь на следующем шаге для сравнения (Singola/Doppia — комната, Monolocale/Bilocale — вся квартира).',
  contractLabel: 'Тип договора',
  datesLabel: 'Срок договора',
  datesHelp: 'Выберите даты начала и окончания в календаре.',
  startLabel: 'Начало',
  endLabel: 'Конец',
  datesRequired: 'Даты начала и окончания обязательны. Бессрочные объявления не допускаются.',
  duration: 'Срок',
  months: 'мес.',
  monthsUnit_one: '{n} мес.',
  monthsUnit_other: '{n} мес.',
  clearDates: 'Очистить даты',
  pickStartFirst: 'Сначала выберите день начала',
  pickEnd: 'Теперь выберите день окончания',
  endBeforeStart: 'Окончание должно быть после начала.',

  roomAreaLabel: 'Комната (м²)',
  aptAreaLabel: 'Квартира (м²)',
  bathroomsLabel: 'Ванные',
  areaError: 'Укажите',
  heatingLabel: 'Отопление',
  amenitiesLabel: 'Удобства',
  groupComfort: 'Комфорт',
  groupMobility: 'Транспорт',
  groupRules: 'Правила дома',
  bikeDetailsPlaceholder: 'Где? Напр. закрытый двор',
  parkingDetailsPlaceholder: 'Как? Напр. гараж, уличное разрешение',
  descriptionLabel: 'Описание',
  descriptionHelp: 'Расскажите о жилье, районе и условиях договора.',
  descriptionPlaceholder: 'Общее впечатление, транспорт, детали договора…',
  smokingOk: 'Курение разрешено',
  smokingNo: 'Не курить',
  petsOk: 'Можно с животными',
  petsNo: 'Без животных',

  photosLabel: 'Фотографии',
  photosHelp: 'Первое фото — обложка. Перетаскивайте, чтобы менять порядок.',
  photosTips: 'Снимайте горизонтально при дневном свете, покажите комнату, кухню и ванную. Рекомендуется минимум 3 фото.',
  dropHere: 'Перетащите фото сюда',
  orBrowse: 'или выберите на устройстве',
  addByUrl: 'Добавить по ссылке',
  urlPlaceholder: 'https://…/foto.jpg',
  add: 'Добавить',
  cover: 'Обложка',
  makeCover: 'Сделать обложкой',
  remove: 'Удалить',
  moveLeft: 'Влево',
  moveRight: 'Вправо',
  uploading: 'Загрузка',
  uploadFailed: 'Не удалось загрузить',
  similarBadge: 'Похожее фото',
  similarNote: 'Некоторые фото, похоже, используются и в другом объявлении. Используйте только свои фотографии: чужие фото могут привести к удалению объявления и блокировке аккаунта.',
  retry: 'Повторить',
  photoError: 'Добавьте хотя бы одно фото.',
  photoCount: 'Фото: {n}',
  videoTitle: 'Видеотур',
  videoDesc: 'Объявления с видеотуром привлекают больше интереса. Добавьте ссылку на короткое видео о комнате и общих зонах.',
  videoToggle: 'Добавить видеотур',
  videoUrlLabel: 'Ссылка на видео',
  videoUrlHelp: 'Ссылка на файл MP4 / WebM. Идеально 30–90 секунд.',
  moreAngles: 'Добавить другие ракурсы',
  angleDesk: 'Рабочий стол',
  angleKitchen: 'Кухня / общая зона',
  angleBalcony: 'Балкон / вид',

  housematesLabel: 'Сколько человек живёт?',
  housematesHelp: 'Общее число, включая вас.',
  distributionLabel: 'Состав по полу',
  distributionHelp: 'Кто живёт сейчас.',
  women: 'Женщины',
  men: 'Мужчины',
  genderPrefLabel: 'Кого вы ищете?',
  genderAny: 'Не важно',
  genderFemale: 'Только женщины',
  genderMale: 'Только мужчины',
  occupantLabel: 'Жильцы',
  occStudents: 'Только студенты',
  occMixed: 'Смешанный',
  occWorkers: 'Работающие',

  reviewTitle: 'Всё готово?',
  reviewHint: 'Просмотрите сводку перед публикацией.',
  edit: 'Изменить',
  checklistTitle: 'Качество объявления',
  checkPhotos: '3+ фото',
  checkVideo: 'Видеотур',
  checkDescription: 'Описание',
  checkDates: 'Даты договора',
  loginBtn: 'Войти / Регистрация',
  draftRestored: 'Вы продолжаете с того места, где остановились.',
  discardDraft: 'Удалить черновик',

  successTitle: 'Объявление опубликовано!',
  successEdit: 'Изменения сохранены',
  successText: 'Ваше объявление видно в студенческой сети Падуи. Поделитесь ссылкой, чтобы быстрее найти жильца.',
  copyLink: 'Копировать ссылку',
  copied: 'Скопировано',
  share: 'Поделиться',
  viewListing: 'Открыть объявление',
  boostTitle: 'Усильте объявление',
  boostVideo: 'Добавить видеотур',
  boostVideoDesc: 'Объявления с видео получают больше сообщений.',
  boostVerify: 'Подтвердить через UniPD',
  boostVerifyDesc: 'Значок подтверждённого студента вызывает доверие.',
  boostPhotos: 'Добавить фото',
  boostPhotosDesc: 'По фото для каждой комнаты.',
  toMyListings: 'Мои объявления',
};

const hi: Dict = {
  createTitle: 'विज्ञापन पोस्ट करें',
  editTitle: 'विज्ञापन संपादित करें',
  stepOf: 'चरण {n} / {total}',
  step1: 'बुनियादी जानकारी',
  step2: 'किराया और अनुबंध',
  step3: 'घर का विवरण',
  step4: 'फोटो और वीडियो',
  step5: 'हाउसमेट',
  step6: 'पूर्वावलोकन',
  step1Hint: 'आप क्या किराए पर दे रहे हैं और कहाँ?',
  step2Hint: 'किराया, बिल और अनुबंध अवधि',
  step3Hint: 'आकार, सुविधाएँ और नियम',
  step4Hint: 'अच्छी फोटो विज्ञापन को अलग दिखाती हैं',
  step5Hint: 'घर में कौन रहता है, आप किसे ढूँढ रहे हैं?',
  step6Hint: 'अंतिम जाँच और प्रकाशन',
  back: 'वापस',
  next: 'सहेजें और आगे बढ़ें',
  publish: 'विज्ञापन प्रकाशित करें',
  saveChanges: 'बदलाव सहेजें',
  publishing: 'प्रकाशित हो रहा है…',
  saving: 'सहेजा जा रहा है…',
  draftSaved: 'ड्राफ्ट सहेजा गया',
  close: 'बंद करें',
  preview: 'पूर्वावलोकन',
  livePreview: 'लाइव पूर्वावलोकन',
  previewNote: 'खोज में आपका विज्ञापन ऐसा दिखेगा।',
  required: 'आवश्यक',
  optional: 'वैकल्पिक',
  fixFields: 'आगे बढ़ने से पहले चिह्नित फ़ील्ड भरें।',

  roomTypeQ: 'किस प्रकार का कमरा?',
  titleLabel: 'विज्ञापन शीर्षक',
  titleHelp: 'छोटा और स्पष्ट: सड़क, कमरे का प्रकार और एक खासियत।',
  titlePlaceholder: 'Via Forcellini, रोशन सिंगल कमरा',
  titleError: 'शीर्षक जोड़ें।',
  locationLabel: 'पता',
  locationHelp: 'पता लिखें या नक्शे पर पिन खींचें। इलाका अपने आप भर जाएगा।',
  addressPlaceholder: 'Via Forcellini 42, Padova',
  suggestions: 'सुझाव',
  districtLabel: 'इलाका',
  districtAuto: 'लोकेशन से चुना गया',
  nearestUni: 'सबसे नज़दीकी विश्वविद्यालय भवन',
  walk: 'पैदल',
  bus: 'बस से ≈',
  min: 'मिनट',

  rentLabel: 'मासिक किराया',
  rentError: 'किराया दर्ज करें।',
  perMonth: '/ माह',
  expensesLabel: 'बिल',
  expensesIncluded: 'किराए में शामिल',
  expensesExtra: 'अलग से देय',
  expensesAmount: 'मासिक बिल राशि',
  expensesIncludedText: 'बिल शामिल',
  expensesExtraText: 'खर्च',
  radarTitle: 'किराया सूचकांक',
  radarNoData: 'इस कमरे के प्रकार के लिए तुलना डेटा नहीं है।',
  radarAvg: 'इलाके का औसत',
  radarLow: 'किफ़ायती',
  radarFair: 'उचित',
  radarHigh: 'महँगा',
  radarLowMsg: 'इलाके के औसत से कम: जल्दी रुचि मिलेगी।',
  radarFairMsg: 'इलाके के औसत के बराबर: उचित कीमत।',
  radarHighMsg: 'इलाके के औसत से ऊपर: रुचि कम हो सकती है।',
  radarEmpty: 'किराया और क्षेत्रफल दर्ज करें, हम इलाके के प्रति वर्ग मीटर औसत से तुलना करेंगे।',
  radarNeedArea: 'तुलना के लिए अगले चरण में क्षेत्रफल दर्ज करें (Singola/Doppia: कमरा, Monolocale/Bilocale: पूरा घर)।',
  contractLabel: 'अनुबंध का प्रकार',
  datesLabel: 'अनुबंध अवधि',
  datesHelp: 'कैलेंडर से शुरू और समाप्ति तिथि चुनें।',
  startLabel: 'शुरू',
  endLabel: 'समाप्ति',
  datesRequired: 'शुरू और समाप्ति तिथि ज़रूरी है। बिना समाप्ति तिथि के विज्ञापन नहीं दिया जा सकता।',
  duration: 'अवधि',
  months: 'माह',
  monthsUnit_one: '{n} माह',
  monthsUnit_other: '{n} माह',
  clearDates: 'तिथियाँ हटाएँ',
  pickStartFirst: 'पहले शुरू का दिन चुनें',
  pickEnd: 'अब समाप्ति का दिन चुनें',
  endBeforeStart: 'समाप्ति शुरू के बाद होनी चाहिए।',

  roomAreaLabel: 'कमरा (m²)',
  aptAreaLabel: 'अपार्टमेंट (m²)',
  bathroomsLabel: 'बाथरूम',
  areaError: 'दर्ज करें',
  heatingLabel: 'हीटिंग',
  amenitiesLabel: 'सुविधाएँ',
  groupComfort: 'आराम',
  groupMobility: 'आवागमन',
  groupRules: 'घर के नियम',
  bikeDetailsPlaceholder: 'कहाँ? जैसे बंद आँगन',
  parkingDetailsPlaceholder: 'कैसे? जैसे गैराज, सड़क परमिट',
  descriptionLabel: 'विवरण',
  descriptionHelp: 'घर, आस-पड़ोस और अनुबंध की शर्तें बताएँ।',
  descriptionPlaceholder: 'घर का सामान्य हाल, परिवहन, अनुबंध विवरण…',
  smokingOk: 'धूम्रपान की अनुमति',
  smokingNo: 'धूम्रपान निषेध',
  petsOk: 'पालतू जानवर की अनुमति',
  petsNo: 'पालतू जानवर नहीं',

  photosLabel: 'फोटो',
  photosHelp: 'पहली फोटो कवर बनती है। क्रम बदलने के लिए खींचें।',
  photosTips: 'दिन की रोशनी में आड़ी फोटो लें और कमरा, रसोई और बाथरूम दिखाएँ। कम से कम 3 फोटो सुझाई जाती हैं।',
  dropHere: 'फोटो यहाँ छोड़ें',
  orBrowse: 'या डिवाइस से चुनें',
  addByUrl: 'लिंक से जोड़ें',
  urlPlaceholder: 'https://…/photo.jpg',
  add: 'जोड़ें',
  cover: 'कवर',
  makeCover: 'कवर बनाएँ',
  remove: 'हटाएँ',
  moveLeft: 'बाएँ ले जाएँ',
  moveRight: 'दाएँ ले जाएँ',
  uploading: 'अपलोड हो रहा है',
  uploadFailed: 'अपलोड विफल',
  similarBadge: 'मिलती-जुलती फ़ोटो',
  similarNote: 'कुछ फ़ोटो किसी दूसरे विज्ञापन में भी इस्तेमाल हुई दिखती हैं। केवल अपनी खींची हुई फ़ोटो इस्तेमाल करें; दूसरों की फ़ोटो से आपका विज्ञापन हटाया जा सकता है और खाता बंद हो सकता है।',
  retry: 'फिर कोशिश करें',
  photoError: 'कम से कम एक फोटो जोड़ें।',
  photoCount: '{n} फोटो',
  videoTitle: 'वीडियो टूर',
  videoDesc: 'वीडियो टूर वाले विज्ञापनों को अधिक रुचि मिलती है। कमरे और साझा जगहों के छोटे वीडियो का लिंक जोड़ें।',
  videoToggle: 'वीडियो टूर जोड़ें',
  videoUrlLabel: 'वीडियो लिंक',
  videoUrlHelp: 'MP4 / WebM फ़ाइल का लिंक। 30-90 सेकंड आदर्श है।',
  moreAngles: 'और कोण जोड़ें',
  angleDesk: 'स्टडी टेबल',
  angleKitchen: 'रसोई / साझा जगह',
  angleBalcony: 'बालकनी / दृश्य',

  housematesLabel: 'घर में कितने लोग रहते हैं?',
  housematesHelp: 'आपको मिलाकर कुल संख्या।',
  distributionLabel: 'लिंग अनुपात',
  distributionHelp: 'अभी कौन रहता है।',
  women: 'महिलाएँ',
  men: 'पुरुष',
  genderPrefLabel: 'आप किसे ढूँढ रहे हैं?',
  genderAny: 'कोई फर्क नहीं',
  genderFemale: 'केवल महिलाएँ',
  genderMale: 'केवल पुरुष',
  occupantLabel: 'निवासी',
  occStudents: 'केवल छात्र',
  occMixed: 'मिश्रित',
  occWorkers: 'कामकाजी',

  reviewTitle: 'सब तैयार है?',
  reviewHint: 'प्रकाशित करने से पहले सारांश देख लें।',
  edit: 'संपादित करें',
  checklistTitle: 'विज्ञापन की गुणवत्ता',
  checkPhotos: '3+ फोटो',
  checkVideo: 'वीडियो टूर',
  checkDescription: 'विवरण',
  checkDates: 'अनुबंध तिथियाँ',
  loginBtn: 'लॉगिन / पंजीकरण',
  draftRestored: 'आप वहीं से जारी रख रहे हैं जहाँ छोड़ा था।',
  discardDraft: 'ड्राफ्ट हटाएँ',

  successTitle: 'आपका विज्ञापन लाइव है!',
  successEdit: 'बदलाव सहेजे गए',
  successText: 'आपका विज्ञापन पदुवा छात्र नेटवर्क में दिख रहा है। जल्दी रुचि पाने के लिए लिंक साझा करें।',
  copyLink: 'लिंक कॉपी करें',
  copied: 'कॉपी हो गया',
  share: 'साझा करें',
  viewListing: 'विज्ञापन देखें',
  boostTitle: 'अपने विज्ञापन को मज़बूत करें',
  boostVideo: 'वीडियो टूर जोड़ें',
  boostVideoDesc: 'वीडियो वाले विज्ञापनों को अधिक संदेश मिलते हैं।',
  boostVerify: 'UniPD से सत्यापित करें',
  boostVerifyDesc: 'सत्यापित छात्र बैज भरोसा बढ़ाता है।',
  boostPhotos: 'और फोटो जोड़ें',
  boostPhotosDesc: 'हर कमरे की एक फोटो हो।',
  toMyListings: 'मेरे विज्ञापन',
};

export const WIZARD_TEXT: Record<Language, Dict> = { tr, en, it, de, ru, hi };
export type WizardText = Dict;

export { LANG_LOCALE } from './locale';

export const fill = (text: string, vars: Record<string, string | number>) =>
  text.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));
